sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y xfonts-75dpi chromium-browser fonts-noto language-pack-zh-hant fonts-wqy-microhei ttf-wqy-microhei fonts-wqy-zenhei ttf-wqy-zenhei
  - wget https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.trusty_amd64.deb
  - sudo dpkg -i wkhtmltox_0.12.5-1.trusty_amd64.deb
  - rm wkhtmltox_0.12.5-1.trusty_amd64.deb
install:
  - fc-cache -f -v
script:
  - make html pdf
deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
