language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_install:
  - sudo apt install chromium-browser
install:
  - npm install
script:
  - wget --quiet https://github.com/jgm/pandoc/releases/download/2.2.3.2/pandoc-2.2.3.2-1-amd64.deb
  - sudo dpkg -i pandoc-2.2.3.2-1-amd64.deb
  - rm pandoc-2.2.3.2-1-amd64.deb
  - pandoc --version
  - make html pdf
deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
